services:
  - type: web
    name: my-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libjpeg8 libxrender1 libxext6 libfontconfig1
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: oregon
